// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  Statement = 2,
  Path = 3,
  Divider = 4,
  Segment = 5,
  Space = 6,
  Text = 7,
  Number = 8,
  Char = 9,
  Symbol = 10
