// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hOVQPOOOOQO'#Ca'#CaQVQPOOOOQO-E6_-E6_",
  stateData: "b~OWOS~OQPORPOSPO~O",
  goto: "]UPPPPPVQQORRQ",
  nodeNames: "⚠ File Identifier Number String",
  maxTerm: 8,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "$Q~R]X^zpqzrs!o!P!Q#^!Q![#x#y#zz$f$gz#BY#BZz$IS$I_z$I|$JOz$JT$JUz$KV$KWz&FU&FVz~!PYW~X^zpqz#y#zz$f$gz#BY#BZz$IS$I_z$I|$JOz$JT$JUz$KV$KWz&FU&FVz~!rTOr!ors#Rs;'S!o;'S;=`#W<%lO!o~#WOS~~#ZP;=`<%l!o~#aR!c!}#j#R#S#j#T#o#j~#oRQ~!c!}#j#R#S#j#T#o#j~#}PR~!Q![#x",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
